# Generated by Django 5.2.4 on 2026-06-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vs', '0002_alter_product_image_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='s', max_length=5),
            preserve_default=False,
        ),
    ]
