# Generated by Django 5.2.4 on 2026-06-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vs', '0004_remove_order_product_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('New Arrivals', 'New Arrivals')], default='Men', max_length=50),
        ),
    ]
