# Generated by Django 5.2.4 on 2026-06-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vs', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('New Arrivals', 'New Arrivals'), ('kids', 'kids')], default='Men', max_length=50),
        ),
    ]
