# Generated by Django 5.2.4 on 2026-06-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vs', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
